### ISSUE TITLE
Blueprints - Plugins Page - Choosing more than one file is overwritten

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#61] opened 2016-10-28 04:18 UTC
Click +/New, select shell from drop down to create a new plugin. Click on Action button at top right, click Import. Import Plugin page is opened asking to Choose File or Import. Click Choose File, to select files from disk. On choosing more than one file, is showing only the last one chosen. Choosing more than one file is overwritten.
![choose file-5](https://cloud.githubusercontent.com/assets/16450606/19794858/a6fc634e-9cf3-11e6-9477-324109665544.png)

**Comment by intesar** [comment] 2016-10-28 04:20
This is not a bug, the functionality works as designed. Please close this.

**Closed by intesar** 2016-10-28 04:20 UTC
